### ISSUE TITLE
Run deepest on datasets of unequal size

### ISSUE THREAD

**Issue by dgautheret** [salzmanlab/DEEPEST-Fusion#2]
Dear authors, we would like to run Deepest on our own dataset of 1000 tumor samples. We wonder whether the different cohort size will affect the expectation statistics and thus could lead to a significantly different call sensitivity than in your TCGA study. What would be the best overall strategy if we want to compare fusion calls between TCGA and our own cohort? 
All the best,
Daniel

**Comment by roozbehdn** [comment]
Hello, the main issue with analyzing large datasets is the false positives due to multiple hypothesis testing. However, by the way that the SBT-based postprocessing step in deepest has been designed, deepest is able to identify those false positives. If you want to compare two datasets with different sampling/sequencing depths you should account for those differences in your comparison. For example, regarding the prevalence of fusions, you can compare the average number of fusions per sample or per 10^6 reads.
